name: CI

on:
  pull_request:
  push:

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - run: sudo apt-get update && sudo apt-get install aspell aspell-en
      - name: Install mdbook
        uses: taiki-e/install-action@mdbook
      - name: Install mdbook-linkcheck
        uses: taiki-e/install-action@mdbook-linkcheck
      - run: bash ci/spellcheck.sh list
      - run: mdbook build
      - run: cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target
      - uses: actions/upload-pages-artifact@v3
        with:
          path: book/html
        # if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'rust-lang'

  deploy:
    name: deploy
    needs: test
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'rust-lang'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
